fix : Api users connect
webpress-vn/user-manager pull request #32
Opened 2021-11-04 05:02 UTC by minhquang19

- Read data from token on header
- Check, create users from token and return user's token

2021-11-05 01:41 UTC, sonhaichu requested changes

2021-11-05 01:41 UTC, sonhaichu commented on src/app/Http/Controllers/ConnectController.php
> +                return response([
@minhquang19 Chỗ này em throw exception `UnauthorizedHttpException` để đúng status code trả về là 401 nhé.
Danh sách các exception em xem thêm ở đây: https://github.com/dingo/api/wiki/Errors-And-Error-Responses

2021-11-05 01:41 UTC, sonhaichu commented on src/app/Http/Controllers/ConnectController.php
> +    public function JWTDecode($token)
@minhquang19 Chỗ này em không dùng dc hàm của JWT có lẽ vì thiếu biến `JWT_SECRET ` trong file .env.
Em thử làm theo hướng dẫn này để thêm biết đó trong env và thử dùng lại hàm của JWT xem có dc ko.
https://github.com/webpress-vn/core#config-and-migration

2021-11-05 01:41 UTC, sonhaichu commented on src/app/Http/Controllers/ConnectController.php
> +            $user = $this->repository->findByField('email', $email)->first();
@minhquang19 Mình có thể viết chung đoạn lấy thông tin user hoặc tạo mới vào một hàm `firstOrCreate` trong repository để code clear hơn

2021-11-05 01:41 UTC, sonhaichu commented on src/routes/api.php
> +        $api->post('refresh', 'VCComponent\Laravel\User\Contracts\Auth@refresh');
@minhquang19 Tại sao mình cần thêm 2 api này em nhỉ?

2021-11-05 01:41 UTC, sonhaichu commented on tests/Feature/Api/User/UserTest.php
> +    public function can_connect_user_by_api_router()
@minhquang19 Phần này em viết ra một file test khác giúp anh nhé.

2021-11-05 04:29 UTC, sonhaichu commented on tests/Feature/Api/User/UserConnectTest.php
> +        $token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTYzNTkzMTk1NywiZXhwIjo0MjI3OTMxOTU3fQ.ndiJq4bMWXi9X4K5Fm7Seqe2zOIw7UwFS575K081jmE";
@minhquang19 để chỗ này chuẩn hơn thì mình có generate được token từ một mảng data có sẵn không em nhỉ?

2021-11-05 04:30 UTC, sonhaichu commented on src/app/Http/Controllers/ConnectController.php
> +            // $payload = JWTAuth::getPayload($token)->toArray();
@minhquang19 vẫn ko dùng được hàm này à em?

2021-11-05 06:44 UTC, minhquang19 commented on src/app/Http/Controllers/ConnectController.php
> +            // $payload = JWTAuth::getPayload($token)->toArray();
không được a ạ, e thử config lại nhưng vẫn lỗi

2021-11-05 07:12 UTC, minhquang19 commented on tests/Feature/Api/User/UserConnectTest.php
> +        $token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTYzNTkzMTk1NywiZXhwIjo0MjI3OTMxOTU3fQ.ndiJq4bMWXi9X4K5Fm7Seqe2zOIw7UwFS575K081jmE";
oke a

2021-11-06 02:33 UTC, minhquang19 commented on src/app/Http/Controllers/ConnectController.php
> +            // $payload = JWTAuth::getPayload($token)->toArray();
E đọc trên stackoverflow thấy bảo JWTAuth:getPayload chỉ lấy được khi token có JWT_SECRET giống nhau thôi a ạ, e thử đổi token khác thì nó nhận ngay. còn token từ Api Webpress login thì k nhận

2021-11-08 04:14 UTC, sonhaichu approved these changes

2021-11-08 04:14 UTC, merged